### ISSUE TITLE
UnicodeDecodeError running in Windows

### ISSUE THREAD

**Issue by jocolamarco** [nathan-sain/foundry-world-tools#10]
Get the following error when running the tool in Windows:

`UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 1162: character maps to <undefined>`

EDIT: I was able to workaround this by activating a beta feature in Windows10

**Comment by nathan-sain** [comment]
@jocolamarco I'm interested to know  what feature you enabled in order to get around this error. 

Unfortunately, It seems the 0x9d character doesn't have a corresponding entry in the utf-8 character map. I'm curious what format the the file on your system is? If there are other reports of errors related to charmaps I may use the chardet module to attempt to determine the encoding of files before reading from them.

**Comment by jocolamarco** [comment]
I used notepad++ and sublime console features to check system encoding in
win10. It came up as 'undefined'.
Then, after some googling, i went into advanced settings and enabled the
following:

"Beta: Use Unicode UTF-8 for worldwide language support".

*All Settings -> Time & Language -> Language -> "Administrative Language
Settings*

A domingo, 6/06/2021, 20:18, Nathan Sain ***@***.***>
escreveu:

**Comment by nathan-sain** [comment]
Thanks for the information and your solution. I'm going to close this issue. I'll reopen it if character encoding on Windows continues to be a general problem.
